"""
Django settings for Project_Inventory_Management_System project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECRET_KEY = 'django-insecure-1_k+sw+w_f+e%nn)hy_4kq(e6p!cu_v^5cm$xt(_g$^%8t!5=^'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-1_k+sw+w_f+e%nn)hy_4kq(e6p!cu_v^5cm$xt(_g$^%8t!5=^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['.pythonanywhere.com','mohamedabdo.pythonanywhere.com']

MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = BASE_DIR / 'media'

# Application definition

INSTALLED_APPS = [
    'orders',
    'widget_tweaks',
    'products.apps.ProductsConfig',
    'users.apps.UsersConfig',
    'shipments.apps.ShipmentsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Project_Inventory_Management_System.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project_Inventory_Management_System.wsgi.application'

#Mohamed create a database for the project
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',   
#         'NAME': 'inventory_DB',             
#         'USER': 'inventory_user',                 
#         'PASSWORD': '01006641942',               
#         'HOST': '127.0.0.1',                       
#         'PORT': '5432',                            
#     }
# }

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'inventory_db',
#         'USER': 'inventory_user',
#         'PASSWORD': '1067858110',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'inventory_db',
#         'USER': 'inventory_user',
#         'PASSWORD': '1067858110',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',  # Engine for PostgreSQL
#         'NAME': 'test',                             # Name of your database
#         'USER': 'test',                             # Your PostgreSQL username
#         'PASSWORD': 'test1234',                     # Your PostgreSQL password
#         'HOST': 'localhost',                        # Database server address
#         'PORT': '5432',                             # Default port for PostgreSQL
#     }
# }
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     BASE_DIR / "static", 
#     BASE_DIR / "home/static",  
# ]
# STATIC_ROOT = str(BASE_DIR / 'staticfiles')

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    str(BASE_DIR / "static"), 
    str(BASE_DIR / "home/static"),  
]
STATIC_ROOT = '/home/mohamedabdo/Project-Django/staticfiles'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'  
LOGOUT_REDIRECT_URL = 'login'
AUTH_USER_MODEL = 'users.CustomUser' # To tell Django to use this user


# Security settings for production
SECURE_HSTS_SECONDS = 31536000  # Force browser to use HTTPS
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = True  # Redirect HTTP -> HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True