# Generated by Django 5.2.4 on 2025-07-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
